name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Cache bazel
        uses: actions/cache@v2.1.4
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-name }}

      - uses: actions/checkout@v2

      # build
      - name: Build the code
        run: bazel build //...

      # test
      - name: Test the code
        run: bazel test //...

      # test
      - name: Run Clang-tidy
        run: make tidy 2>&1 | tee clang-tidy-output.txt

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          cargo install clang-tidy-sarif

      - name: Convert to SARIF
        run: |
          clang-tidy-sarif --input clang-tidy-output.txt --output results.sarif

      - name: Upload SARIF Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

